### ISSUE TITLE
Version 2

### ISSUE THREAD

**Issue by mmoreram** [mmoreram/ControllerExtraBundle#102]
I'm working on what will be new version 2 of the bundle.
This work will be appended in branch *feature/version-2* and will not be BC break unless you've overridden some parts of the bundle, so if you just use the bundle as shown in the documentation, you'll be able to upgrade without any kind of problem. Otherwise, you'll find an upgrade file.

Here some points
- [x] Close the classes visibility by turning everything private and all classes final. This will help composition over inheritance
- [x] Use [BaseBundle](http://github.com/mmoreram/BaseBundle) to reduce some parts complexity. Tests complexity will be reduced as well
- [x] These unit testing scenarios are useless, so will be removed. Instead of that, some extra functional tests will be added to cover more rare cases
- [x] Updated minimum PHP version to 7.1 in order to be able to use BaseBundle. Lets make this step all of us. Old users will continue being able to use old versions of this bundle.
- [x] New extension point for providers will be introduced. New DIC services and parameters providers will be added
- [ ] ~~New annotation `@Service` and `@Parameter`, a way of remove usage of container~~ Has no sense at all...

What do you think?

**Comment by klinkin** [comment]
💯

**Comment by mmoreram** [comment]
Merged https://github.com/mmoreram/ControllerExtraBundle/pull/103 and tagged to **2.0.0** with all these features.
