### ISSUE TITLE
@JsonResponse Ignored When Using JMSSecurityExtraBundle

### ISSUE THREAD

**Issue by sidux** [mmoreram/ControllerExtraBundle#34]
When i use the annotation Secure of the JMSSecurityExtraBundle the annotation JsonResponse get ignored and i get LogicException "The controller must return a response".

**Comment by mmoreram** [comment]
@sidux ping! Still failing?

**Comment by sidux** [comment]
Hi, 
i don't use JMSSecurityExtraBundle anymore, replaced it with SensioFrameworkExtraBundle and it works fine :+1:
