### ISSUE TITLE
Support FormAnnotation with no form parameter

### ISSUE THREAD

**Issue by xphere** [mmoreram/ControllerExtraBundle#42]
Sometimes we don't need the `Form` nor the `FormView` but still want the magic behind `FormAnnotation`. It would be nice to have no `$form` parameter in the `Controller`, if we're not going to use it anyway.

Now it checks for the class of the parameter and crashes if it does not exist (or if the type-hint is not a class)

**Comment by mmoreram** [comment]
@xphere Well, make sense to inject the element even if is not used.

**Comment by xphere** [comment]
It may be used in other annotations, but it should not force the method to have it as a parameter, that was the point. I'll work in a PR, it looks easy.
