### ISSUE TITLE
Get Query or Post params on annotation

### ISSUE THREAD

**Issue by rogergros** [mmoreram/ControllerExtraBundle#54]
It will be a good idea to direcly access to the query and post parameters from the annotations.

`GET /page?foo=bar`

And you could get this parameters from:

```php
<?php
//...
/**
 * ...
 * @Get(
 *      path = "foo",
 *      name = "varName"
 *      default = false,
 *      deep = false
 * )
 * ...
 */
public function anyAction(
    $varName
) {
    echo $varName;
    // This would print 'bar'
}
```

Same would work for post requests:

`POST /page`

Body:

```
foo=bar
```

And you could get this parameters from:

```php
<?php
//...
/**
 * ...
 * @Post(
 *      path = "foo",
 *      name = "varName"
 *      default = false,
 *      deep = false
 * )
 * ...
 */
public function anyAction(
    $varName
) {
    echo $varName;
    // This would print 'bar'
}
```

> Both would call the parameterBag get method.

Optional parameters:
- name (The name should be the same than the original path"
- default (Default parameterBag value)
- deep (Default parameterBag value)

**Comment by rogergros** [comment]
@mmoreram If you agree, I could do the development ;)

**Comment by mmoreram** [comment]
Feel free :)
