### ISSUE TITLE
Multiple paginator params don't work

### ISSUE THREAD

**Issue by jcornide** [mmoreram/ControllerExtraBundle#70]
Hi,
I think I found an issue when adding multiple where params to the paginator. It seems something like:
```php
    *      wheres = {
    *          {"x", "code", "=", "GER"},
    *          {"x", "dial", "=", "49"},
    *      }
```
doesn't work, it only loads the value of the last param and the query executed is like this:
`WHERE c0_.code = '49' AND c0_.dial = '49' ORDER BY c0_.code ASC) dctrn_result) dctrn_table

I've looking into the code and I think I found the problem: in the evaluate method of the PaginatorWheresEvaluator you initialize interation:
```php
        $iteration = 0;
```
but I think the $iterations++; is missing in the foreach loop.

I tried by adding it and it works perfectly now, here's the method:
```php
public function evaluate(
        QueryBuilder $queryBuilder,
        AnnotationPaginator $annotation
    )
    {
        $iteration = 0;

        if (is_array($annotation->getWheres())) {

            foreach ($annotation->getWheres() as $where) {

                $whereValue = $this
                    ->requestParameterProvider
                    ->getParameterValue($where[3]);

                $optionalFilter = (boolean) isset($where[4])
                    ? $where[4]
                    : false;

                if ($optionalFilter && ($where[3] === $whereValue)) {

                    continue;
                }

                $queryBuilder
                    ->andWhere(trim($where[0]) . '.' . trim($where[1]) . " " . $where[2] . " ?0" . $iteration)
                    ->setParameter("0" . $iteration, $whereValue);
                # The missing iteration
                $iteration++;
            }
        }

        return $this;
    }
```

**Comment by mmoreram** [comment]
This line is already in the code...

https://github.com/mmoreram/ControllerExtraBundle/blob/master/Resolver/Paginator/PaginatorWheresEvaluator.php#L81

I've tagged the repository. Now you should get the fixed version :)

Thanks!

**Comment by jcornide** [comment]
Great! thanks!
