### ISSUE TITLE
Header annotation

### ISSUE THREAD

**Issue by sebastianblum** [mmoreram/ControllerExtraBundle#76]
Hello!

Thank you for the bundle, it looks great and we will use it in the future.
We use this code several times:

```
public function special...Action(Project $project)
{
    $response = $this->render(
        '@AppBundle/special....html.twig',
        array(
            'project' => $project,
        )
    );

    $response->headers->set('Access-Control-Allow-Origin', '*');

    return $response;
}
```

It would be great if we can introduce a header-annotation like

```
@Header('Access-Control-Allow-Origin', '*')
or
@AddHeader('Access-Control-Allow-Origin', '*')
```

**Comment by mmoreram** [comment]
Hi there @sebastianblum !

Well, that's a good idea indeed :)

**Comment by JHGitty** [comment]
I think `@AddHeader` sounds better.

**Comment by mmoreram** [comment]
There is a project for this :)
https://github.com/mmoreram/HTTPHeadersBundle

**Comment by JHGitty** [comment]
The last commit was February 2014 and I don't see annotations there.

**Comment by mmoreram** [comment]
That's because this project is not for annotations, but for all project. Of course you cannot add headers by using annotations, but could be an extra thing :)
