### ISSUE TITLE
Wildcard % not working properly

### ISSUE THREAD

**Issue by jcornide** [mmoreram/ControllerExtraBundle#80]
Hi,
I think I found a small bug in the Where section of the pagination.

When I try to add a parameter like this:

``` php
wheres = {
    *          {"x", "code", "LIKE", "code%", true},
    *      }
```

it seems like it doesn't work.

Looking into the code I think I fund the problem, in the addWildCards method of the PaginatorWheresEvaluator:

``` php
 $hasInitialPercentage = (strpos($annotationWhereParameter, '%') === 0);
        $hasEndPercentage = (strpos($annotationWhereParameter, '%') === 0);
        if ($hasInitialPercentage) {
            $whereValue = '%' . $whereValue;
        }
        if ($hasEndPercentage) {
            $whereValue = $whereValue . '%';
        }

        return $whereValue;
```

The $hasEndPercentage uses the same condition as the hasIniticialPercentage. Could that be the problem? Thanks!

**Comment by JHGitty** [comment]
You are right. It's a bug.

Wrong line in code:
https://github.com/mmoreram/ControllerExtraBundle/blob/51b5743c520f3bf9c67300a6b5fb333d27eaed12/Resolver/Paginator/PaginatorWheresEvaluator.php#L111

Wrong:
```php
$hasEndPercentage = (strpos($annotationWhereParameter, '%') === 0);
```

This should work:
```php
$hasEndPercentage = (substr($annotationWhereParameter, -1) === '%');
```

**Somebody should create a Pull Request.**

**Comment by JHGitty** [comment]
I think the function should be simplified:

```php
    private function addWildcards($annotationWhereParameter, $whereValue)
    {
        if (strpos($annotationWhereParameter, '%') === 0) {
            $whereValue = '%' . $whereValue;
        }
        if ((substr($annotationWhereParameter, -1) === '%')) {
            $whereValue = $whereValue . '%';
        }
        return $whereValue;
    }
```

**Comment by mmoreram** [comment]
@jcornide One year and a half later... #101

Thanks for the report and sorry for this time :(
