### ISSUE TITLE
PaginatorAnnotation Factory Pattern

### ISSUE THREAD

**Issue by spicyroland** [mmoreram/ControllerExtraBundle#87]
Hi Marc,
I would like to be able to use a service container object (@elcodi.store) in your wheres clause

```
@PaginatorAnnotation(
     *      attributes = "paginatorAttributes",
     *      class = "elcodi.entity.product.class"
     *      page = "~page~",
     *      limit = 6
     *      wheres = {
     *          {"x", "enabled", "=", true},
     *          {"x", "showInHome", "=", true},
     *          {"x", "store", "=", "@elcodi.store"},
     *      },
```

..unfortunately I could not manage to get this running. Any ideas? 
Thx
 Roland

**Comment by mmoreram** [comment]
Hmmm, this is not possible at the moment...
This would be some nice development then. At the moment the value is computed, try to solve it as a service as well :dancer: 

Could you please try it?

If yes, don't hesitate to ping me for any trouble :)

Remember to test as well :D

Thanks! ^^

**Comment by JHGitty** [comment]
What should exactly happen?
Would you like to use the result of the ``__toString()`` function of ``elcodi.store``?

**Comment by mmoreram** [comment]
@JHGitty you can define anything as a service, and in that case, `@elcodi.store` is an entity generated by a factory.

This could be implemented by adding a new provider (DIC service or parameter). I will try it now :)

**Comment by mmoreram** [comment]
@JHGitty version 2.0.0 created with providers collector.
You can now add this feature :)

Thanks.
