### ISSUE TITLE
PaginatorWheresEvaluator bug

### ISSUE THREAD

**Issue by skillberto** [mmoreram/ControllerExtraBundle#99]
Hi!

If I think well, here you wanna put back the **%** sign:

```
    private function addWildcards($annotationWhereParameter, $whereValue)
    {
        $hasInitialPercentage = (strpos($annotationWhereParameter, '%') === 0);
        $hasEndPercentage = (strpos($annotationWhereParameter, '%') === 0);
        if ($hasInitialPercentage) {
            $whereValue = '%' . $whereValue;
        }
        if ($hasEndPercentage) {
            $whereValue = $whereValue . '%';
        }
        return $whereValue;
    }
```

But, the second `strpos` line is same with the first one, so you put **%** back and forth in any case, if it was the first char.

In my opinion, it's need to be `stripos` for the correct work.

**Comment by mmoreram** [comment]
@skillberto YES! You're right!
Thanks, I'm going to fix it right now!

**Comment by mmoreram** [comment]
@skillberto can you check #101 ?
